### ISSUE TITLE
get single user data when query seed of multiple user with 'results' parameter

### ISSUE THREAD

**Issue by gianfabiopezzolla** [RandomAPI/Randomuser.me-Node#173]
Hi there,

I have notice querying `https://randomuser.me/api/?results=5000`, for example, that the seed is available for data set, but not inside single user object, so how I can retrieve single user data, when I query `https://randomuser.me/api/?results=5000&seed=seedOfDataSet`?

I have tried fetching with `user.id` or `user.login.uuid`, but not seems to work. They return me other random user.

Thanks in advance.

**Comment by JuanPaulino** [comment]
Hello there,
For that you need to use the **seed** parameter.
Example:
To get 5 users:
https://randomuser.me/api/?seed=abc&results=5

![Captura de pantalla 2021-01-18 a las 9 54 59](https://user-images.githubusercontent.com/46343663/104893090-43e31a00-5973-11eb-9db1-a2ddc7080bb2.png)

![Captura de pantalla 2021-01-18 a las 9 56 03](https://user-images.githubusercontent.com/46343663/104893233-75f47c00-5973-11eb-9b22-4c05992f6277.png)

To get a user with the id parameter:
https://randomuser.me/api/?seed=abc&id=INSEE

![Captura de pantalla 2021-01-18 a las 9 57 14](https://user-images.githubusercontent.com/46343663/104893341-97556800-5973-11eb-9acb-2c480860a9e5.png)


Bye.

**Comment by keitharm** [comment]
Currently seeds are associated with the entire dataset and we are unable to associate at a per user level due to how we generate users. We're able to efficiently generate many users by using a seed per dataset vs a seed for every user.

In regard to fetching only `INSEE` ids, that belongs to the FR nat, so you'd need to query with `nat=FR`.
